package id.tentuin.agent.ui.theme
import androidx.compose.ui.graphics.Color
val Primary       = Color(0xFF6C63FF)
val PrimaryLight  = Color(0xFFEEEDFF)
val PrimaryDark   = Color(0xFF4F46E5)
val Background    = Color(0xFFF7F8FA)
val Surface       = Color(0xFFFFFFFF)
val SurfaceVar    = Color(0xFFF3F4F6)
val TextPrimary   = Color(0xFF111827)
val TextSub       = Color(0xFF374151)
val TextMuted     = Color(0xFF9CA3AF)
val Border        = Color(0xFFE5E7EB)
val Success       = Color(0xFF10B981)
val Error         = Color(0xFFEF4444)
val Warning       = Color(0xFFF59E0B)
